### PR TITLE
detect line endings based on text not on OS

### PR DESCRIPTION
**Pull request by schoes**
Hello i made a fix to detect the line endings inside the text and not based on the OS Platform.
regards, the new method is 'detectLineEnding()' and will be used in ' transformContent(content, params, dest)'
Thanks for merging
Regards

### CODE REVIEW

**Comment by schoes** [comment]
you can just check the last commit

**Comment by schoes** [comment]
there is still a little bug to be fixed in my PR. so let me fix it and i will inform you again

**Comment by schoes** [comment]
not used anymore. fixed it in our source code. problem was the linefeed

**Comment by SomaticIT** [comment]
Hi @schoes,
Sorry for my late answer.

I just improved the tag search management to avoid the linefeed issue and allows nested tag management.
You can also use the new `EOL` option to force a specific linefeed.

Changes are published to NPM in version 0.5.3

**Pull request closed without merging**
